# Generated by Django 4.1.1 on 2022-12-15 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sourse_abc_to_mti'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseOld',
        ),
    ]
